# Generated by Django 2.2.5 on 2019-09-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0004_auto_20190916_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
