# Generated by Django 2.2.5 on 2019-09-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0008_auto_20190917_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
