# Generated by Django 2.2.5 on 2019-09-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0011_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
